#!/usr/bin/env bash

set -euo pipefail

OUTPUT_FILE="${OUTPUT_FILE:-./.secrets/sign-documenso.env}"
DOCUMENSO_HOSTNAME="${DOCUMENSO_HOSTNAME:-sign.tomoai.io}"
WEBAPP_URL="${WEBAPP_URL:-https://${DOCUMENSO_HOSTNAME}}"
PORT="${PORT:-3000}"
DOCUMENSO_PORT_BIND="${DOCUMENSO_PORT_BIND:-127.0.0.1}"
POSTGRES_USER="${POSTGRES_USER:-documenso}"
POSTGRES_DB="${POSTGRES_DB:-documenso}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(openssl rand -base64 24 | tr -d '\n')}"
NEXTAUTH_SECRET="${NEXTAUTH_SECRET:-$(openssl rand -hex 32)}"
NEXT_PRIVATE_ENCRYPTION_KEY="${NEXT_PRIVATE_ENCRYPTION_KEY:-$(openssl rand -hex 32)}"
NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY="${NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY:-$(openssl rand -hex 32)}"
NEXT_PRIVATE_SIGNING_PASSPHRASE="${NEXT_PRIVATE_SIGNING_PASSPHRASE:-$(openssl rand -base64 24 | tr -d '\n')}"
NEXT_PUBLIC_DISABLE_SIGNUP="${NEXT_PUBLIC_DISABLE_SIGNUP:-false}"
NEXT_PRIVATE_SMTP_TRANSPORT="${NEXT_PRIVATE_SMTP_TRANSPORT:-smtp-auth}"
NEXT_PRIVATE_SMTP_HOST="${NEXT_PRIVATE_SMTP_HOST:-email-smtp.us-west-2.amazonaws.com}"
NEXT_PRIVATE_SMTP_PORT="${NEXT_PRIVATE_SMTP_PORT:-587}"
NEXT_PRIVATE_SMTP_SECURE="${NEXT_PRIVATE_SMTP_SECURE:-false}"
NEXT_PRIVATE_SMTP_FROM_NAME="${NEXT_PRIVATE_SMTP_FROM_NAME:-Tomo Sign}"
NEXT_PRIVATE_SMTP_FROM_ADDRESS="${NEXT_PRIVATE_SMTP_FROM_ADDRESS:-sign@tomoai.io}"
NEXT_PRIVATE_SMTP_USERNAME="${NEXT_PRIVATE_SMTP_USERNAME:-}"
NEXT_PRIVATE_SMTP_PASSWORD="${NEXT_PRIVATE_SMTP_PASSWORD:-}"
NEXT_PRIVATE_GOOGLE_CLIENT_ID="${NEXT_PRIVATE_GOOGLE_CLIENT_ID:-}"
NEXT_PRIVATE_GOOGLE_CLIENT_SECRET="${NEXT_PRIVATE_GOOGLE_CLIENT_SECRET:-}"
NEXT_PRIVATE_AUTH_GOOGLE_ONLY="${NEXT_PRIVATE_AUTH_GOOGLE_ONLY:-false}"
NEXT_PRIVATE_AUTH_ALLOWED_EMAILS="${NEXT_PRIVATE_AUTH_ALLOWED_EMAILS:-}"
NEXT_PRIVATE_AUTH_ALLOWED_EMAIL_DOMAINS="${NEXT_PRIVATE_AUTH_ALLOWED_EMAIL_DOMAINS:-}"

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

require_command openssl
require_command mkdir

quote_env_value() {
  local value="$1"

  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//\$/\\$}"
  value="${value//\`/\\\`}"

  printf '"%s"' "$value"
}

if [[ -z "$NEXT_PRIVATE_SMTP_USERNAME" || -z "$NEXT_PRIVATE_SMTP_PASSWORD" ]]; then
  echo "Set NEXT_PRIVATE_SMTP_USERNAME and NEXT_PRIVATE_SMTP_PASSWORD before rendering the env file." >&2
  exit 1
fi

mkdir -p "$(dirname "$OUTPUT_FILE")"
umask 177

cat >"$OUTPUT_FILE" <<EOF
DOCUMENSO_HOSTNAME=$(quote_env_value "$DOCUMENSO_HOSTNAME")
DOCUMENSO_PORT_BIND=$(quote_env_value "$DOCUMENSO_PORT_BIND")
PORT=${PORT}
POSTGRES_USER=$(quote_env_value "$POSTGRES_USER")
POSTGRES_PASSWORD=$(quote_env_value "$POSTGRES_PASSWORD")
POSTGRES_DB=$(quote_env_value "$POSTGRES_DB")
NEXTAUTH_SECRET=$(quote_env_value "$NEXTAUTH_SECRET")
NEXT_PRIVATE_ENCRYPTION_KEY=$(quote_env_value "$NEXT_PRIVATE_ENCRYPTION_KEY")
NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=$(quote_env_value "$NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY")
NEXT_PUBLIC_WEBAPP_URL=$(quote_env_value "$WEBAPP_URL")
NEXT_PRIVATE_INTERNAL_WEBAPP_URL=$(quote_env_value "http://documenso:${PORT}")
NEXT_PRIVATE_DATABASE_URL=$(quote_env_value "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}")
NEXT_PRIVATE_DIRECT_DATABASE_URL=$(quote_env_value "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}")
NEXT_PUBLIC_UPLOAD_TRANSPORT=$(quote_env_value "database")
NEXT_PRIVATE_SMTP_TRANSPORT=$(quote_env_value "$NEXT_PRIVATE_SMTP_TRANSPORT")
NEXT_PRIVATE_SMTP_HOST=$(quote_env_value "$NEXT_PRIVATE_SMTP_HOST")
NEXT_PRIVATE_SMTP_PORT=${NEXT_PRIVATE_SMTP_PORT}
NEXT_PRIVATE_SMTP_USERNAME=$(quote_env_value "$NEXT_PRIVATE_SMTP_USERNAME")
NEXT_PRIVATE_SMTP_PASSWORD=$(quote_env_value "$NEXT_PRIVATE_SMTP_PASSWORD")
NEXT_PRIVATE_SMTP_SECURE=${NEXT_PRIVATE_SMTP_SECURE}
NEXT_PRIVATE_SMTP_FROM_NAME=$(quote_env_value "$NEXT_PRIVATE_SMTP_FROM_NAME")
NEXT_PRIVATE_SMTP_FROM_ADDRESS=$(quote_env_value "$NEXT_PRIVATE_SMTP_FROM_ADDRESS")
NEXT_PRIVATE_GOOGLE_CLIENT_ID=$(quote_env_value "$NEXT_PRIVATE_GOOGLE_CLIENT_ID")
NEXT_PRIVATE_GOOGLE_CLIENT_SECRET=$(quote_env_value "$NEXT_PRIVATE_GOOGLE_CLIENT_SECRET")
NEXT_PRIVATE_AUTH_GOOGLE_ONLY=${NEXT_PRIVATE_AUTH_GOOGLE_ONLY}
NEXT_PRIVATE_AUTH_ALLOWED_EMAILS=$(quote_env_value "$NEXT_PRIVATE_AUTH_ALLOWED_EMAILS")
NEXT_PRIVATE_AUTH_ALLOWED_EMAIL_DOMAINS=$(quote_env_value "$NEXT_PRIVATE_AUTH_ALLOWED_EMAIL_DOMAINS")
NEXT_PUBLIC_DISABLE_SIGNUP=${NEXT_PUBLIC_DISABLE_SIGNUP}
NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH=$(quote_env_value "/opt/documenso/cert.p12")
NEXT_PRIVATE_SIGNING_PASSPHRASE=$(quote_env_value "$NEXT_PRIVATE_SIGNING_PASSPHRASE")
EOF

echo "Wrote ${OUTPUT_FILE}"
